### ISSUE TITLE
Does not compile with samtools 0.1.19

### ISSUE THREAD

**Issue by sjackman** [genome/bam-readcount#1]
As reported on [Biostar](http://www.biostars.org/p/63191/#68900).

```
$ make
...
/home/dev/src/samtools/libbam.a(bgzf.o): In function `bgzf_mt':
/home/dev/src/samtools/bgzf.c:445: undefined reference to `pthread_create'
/home/dev/src/samtools/libbam.a(bgzf.o): In function `mt_destroy':
/home/dev/src/samtools/bgzf.c:458: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/bam-readcount] Error 1
make[1]: *** [build/src/exe/bam-readcount/CMakeFiles/bam-readcount.dir/all] Error 2
make: *** [all] Error 2
```
