### ISSUE TITLE
fatal error: compilation failed

### ISSUE THREAD

**Issue by smoretti** [genome/bam-readcount#99]
Hi
I try to compile bam-readcount version 1.0.1 but fail.

I have the same issue than #75 / #78 but the `-fPIC` fix does not solve my problem.
I think the issue could come from _sam.h_ that cannot be found
```
[ 76%] Building CXX object build/src/lib/bamrc/CMakeFiles/bamrc.dir/BasicStat.cpp.o
In file included from /builddir/build/BUILD/bam-readcount-1.0.1/src/lib/bamrc/BasicStat.cpp:1:0:
/builddir/build/BUILD/bam-readcount-1.0.1/src/lib/bamrc/BasicStat.hpp:5:17: fatal error: sam.h: No such file or directory
 #include "sam.h"
                 ^
compilation terminated.
In file included from /builddir/build/BUILD/bam-readcount-1.0.1/src/lib/bamrc/IndelQueueEntry.hpp:3:0,
                 from /builddir/build/BUILD/bam-readcount-1.0.1/src/lib/bamrc/IndelQueueEntry.cpp:1:
/builddir/build/BUILD/bam-readcount-1.0.1/src/lib/bamrc/BasicStat.hpp:5:17: fatal error: sam.h: No such file or directory
 #include "sam.h"
                 ^
compilation terminated.
make[2]: *** [build/src/lib/bamrc/CMakeFiles/bamrc.dir/BasicStat.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [build/src/lib/bamrc/CMakeFiles/bamrc.dir/IndelQueueEntry.cpp.o] Error 1
In file included from /builddir/build/BUILD/bam-readcount-1.0.1/src/lib/bamrc/IndelQueue.hpp:3:0,
                 from /builddir/build/BUILD/bam-readcount-1.0.1/src/lib/bamrc/IndelQueue.cpp:1:
/builddir/build/BUILD/bam-readcount-1.0.1/src/lib/bamrc/BasicStat.hpp:5:17: fatal error: sam.h: No such file or directory
 #include "sam.h"
                 ^
compilation terminated.
make[2]: *** [build/src/lib/bamrc/CMakeFiles/bamrc.dir/IndelQueue.cpp.o] Error 1
make[1]: *** [build/src/lib/bamrc/CMakeFiles/bamrc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
  CC       libcurl_la-url.lo
```

I compile on Linux CentOS 7.9.2009, gcc 6.1.1

**Comment by Rashadx86** [comment]
I had the same sam.h error when reattempting the build in a dirty build environment. make clean && make resolved it for me.
