### ISSUE TITLE
does not compile on OSX 10.9.2 with Samtools 0.1.19-44428cd

### ISSUE THREAD

**Issue by lordzappo** [genome/bam-readcount#9]
[ 50%] Building CXX object CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from /code/bam-readcount/vendor/src/gtest160/src/gtest-all.cc:39:
In file included from /code/bam-readcount/vendor/src/gtest160/include/gtest/gtest.h:57:
In file included from /code/bam-readcount/vendor/src/gtest160/include/gtest/internal/gtest-internal.h:40:
/code/bam-readcount/vendor/src/gtest160/include/gtest/internal/gtest-port.h:499:13: fatal error: 
      'tr1/tuple' file not found
 #   include <tr1/tuple>  // NOLINT
            ^
1 error generated.
make[5]: **\* [CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[4]: **\* [CMakeFiles/gtest.dir/all] Error 2
make[3]: **\* [all] Error 2
make[2]: **\* [vendor/src/gtest160-stamp/gtest160-build] Error 2
make[1]: **\* [CMakeFiles/gtest160.dir/all] Error 2
make: **\* [all] Error 2
